name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: apt install
      run: 
        sudo apt install git build-essential libboost-all-dev libcurl4-gnutls-dev libgtkmm-3.0-dev libgsl-dev liblzma-dev libz-dev libbz2-dev libgzstream0 libgzstream-dev cmake

    - name: make
      run: 
        make
        
    - name: test
      run: 
        ./bin/compare_bed2tss 


